port forwarding

diff --git a/root/etc/cont-init.d/20-run_setup b/root/etc/cont-init.d/20-run_setup
--- a/root/etc/cont-init.d/20-run_setup
+++ b/root/etc/cont-init.d/20-run_setup
@@ -56,80 +56,82 @@ fi
 rm -f /opt/piavpn-manual/token /opt/piavpn-manual/latencyList
 
 # Retry login if no token is generated
-while :; do
-    while :; do
-      # Check for in-line definition of $PIA_USER
-      if [[ ! $PIA_USER || $PIA_USER = "" ]]; then
-        echo
-        read -p "PIA username (p#######): " PIA_USER
-      fi
+# while :; do
+#     while :; do
+#       # Check for in-line definition of $PIA_USER
+#       if [[ ! $PIA_USER || $PIA_USER = "" ]]; then
+#         echo
+#         read -p "PIA username (p#######): " PIA_USER
+#       fi
       
-      # Confirm format of PIA_USER input
-      unPrefix=$( echo ${PIA_USER:0:1} )
-      unSuffix=$( echo ${PIA_USER:1} )
-      if [[ -z "$PIA_USER" ]]; then
-        echo -e "\n${RED}You must provide input.${NC}"
-      elif [[ ${#PIA_USER} != 8 ]]; then
-        echo -e "\n${RED}A PIA username is always 8 characters long.${NC}"
-      elif [[ $unPrefix != "P" ]] && [[ $unPrefix != "p" ]]; then
-        echo -e "\n${RED}A PIA username must start with \"p\".${NC}"
-      elif ! [[ $unSuffix =~ $intCheck ]]; then
-        echo -e "\n${RED}Username formatting is always p#######!${NC}"
-      else
-        echo -e "\n${GREEN}PIA_USER=$PIA_USER${NC}"
-        break
-      fi
-      PIA_USER=""
-    done
-  export PIA_USER
+#       # Confirm format of PIA_USER input
+#       unPrefix=$( echo ${PIA_USER:0:1} )
+#       unSuffix=$( echo ${PIA_USER:1} )
+#       if [[ -z "$PIA_USER" ]]; then
+#         echo -e "\n${RED}You must provide input.${NC}"
+#       elif [[ ${#PIA_USER} != 8 ]]; then
+#         echo -e "\n${RED}A PIA username is always 8 characters long.${NC}"
+#       elif [[ $unPrefix != "P" ]] && [[ $unPrefix != "p" ]]; then
+#         echo -e "\n${RED}A PIA username must start with \"p\".${NC}"
+#       elif ! [[ $unSuffix =~ $intCheck ]]; then
+#         echo -e "\n${RED}Username formatting is always p#######!${NC}"
+#       else
+#         echo -e "\n${GREEN}PIA_USER=$PIA_USER${NC}"
+#         break
+#       fi
+#       PIA_USER=""
+#     done
+#   export PIA_USER
  
-  while :; do
-    # Check for in-line definition of $PIA_PASS
-    if [[ ! $PIA_PASS || $PIA_PASS = "" ]]; then
-      echo
-      echo -n "PIA password: "
-      read -rs PIA_PASS
-      echo
-    fi
+#   while :; do
+#     # Check for in-line definition of $PIA_PASS
+#     if [[ ! $PIA_PASS || $PIA_PASS = "" ]]; then
+#       echo
+#       echo -n "PIA password: "
+#       read -rs PIA_PASS
+#       echo
+#     fi
   
-    # Confirm format of PIA_PASS input
-    if [[ -z "$PIA_PASS" ]]; then
-      echo -e "\n${RED}You must provide input.${NC}"
-    elif [[ ${#PIA_PASS} -lt 8 ]]; then
-      echo -e "\n${RED}A PIA password is always a minimum of 8 characters long.${NC}"
-    else
-      echo -e "\n${GREEN}PIA_PASS input received.${NC}"
-      echo
-      break
-    fi
-    PIA_PASS=""
-  done
-  export PIA_PASS
+#     # Confirm format of PIA_PASS input
+#     if [[ -z "$PIA_PASS" ]]; then
+#       echo -e "\n${RED}You must provide input.${NC}"
+#     elif [[ ${#PIA_PASS} -lt 8 ]]; then
+#       echo -e "\n${RED}A PIA password is always a minimum of 8 characters long.${NC}"
+#     else
+#       echo -e "\n${GREEN}PIA_PASS input received.${NC}"
+#       echo
+#       break
+#     fi
+#     PIA_PASS=""
+#   done
+#   export PIA_PASS
 
   # Confirm credentials and generate token
-  . /usr/local/sbin/get_token.sh
+. /usr/local/sbin/get_token.sh
 
-  tokenLocation="/opt/piavpn-manual/token"
-  # If the script failed to generate an authentication token, the script will exit early.
-  if [ ! -f "$tokenLocation" ]; then
-    read -p "Do you want to try again ([N]o/[y]es): " tryAgain
-    if ! echo ${tryAgain:0:1} | grep -iq y; then
-      exit 1
-    fi
-    PIA_USER=""
-    PIA_PASS=""
-  else
-    PIA_TOKEN=$( awk 'NR == 1' /opt/piavpn-manual/token )
-    export PIA_TOKEN
-    rm -f /opt/piavpn-manual/token
-    break
+tokenLocation="/opt/piavpn-manual/token"
+# If the script failed to generate an authentication token, the script will exit early.
+if [ ! -f "$tokenLocation" ]; then
+  #read -p "Do you want to try again ([N]o/[y]es): "
+  tryAgain="N"
+  if ! echo ${tryAgain:0:1} | grep -iq y; then
+    exit 1
   fi
-done
+  PIA_USER=""
+  PIA_PASS=""
+else
+  PIA_TOKEN=$( awk 'NR == 1' /opt/piavpn-manual/token )
+  export PIA_TOKEN
+  rm -f /opt/piavpn-manual/token
+  #break
+fi
+#done
 
 # Check for in-line definition of PIA_PF and prompt for input
 if [[ ! $PIA_PF || $PIA_PF = "" ]]; then
   echo -n "Do you want a forwarding port assigned ([N]o/[y]es): "
-  read portForwarding
+  #read portForwarding
+  portForwarding="y"
   echo
   if echo ${portForwarding:0:1} | grep -iq y; then
     PIA_PF="true"
@@ -208,7 +210,8 @@ while :; do
     if [[ $selectServer = "ask" ]]; then
       echo -n "Do you want to manually select a server, instead of auto-connecting to the
 server with the lowest latency ([N]o/[y]es): "
-      read selectServer
+      #read selectServer
+      selectServer="N"
       echo
     fi
 
@@ -233,7 +236,8 @@ For example, you can try 0.2 for 200ms allowed latency.
       MAX_LATENCY=0.05 # default
       while :; do
         if [[ ! $latencyInput || $latencyInput = "" ]]; then
-          read -p "Custom latency (no input required for 50ms): " latencyInput
+          #read -p "Custom latency (no input required for 50ms): " latencyInput
+          latencyInput=0.1
           echo
         fi
         customLatency=0
@@ -284,7 +288,8 @@ For example, you can try 0.2 for 200ms allowed latency.
       
         # Receive input to specify the server to connect to manually
         while :; do 
-          read -p "Input the number of the server you want to connect to ([1]-[$i]) : "  serverSelection
+          #read -p "Input the number of the server you want to connect to ([1]-[$i]) : "  serverSelection
+          serverSelection=1
             if [[ -z "$serverSelection" ]]; then
               echo -e "\n${RED}You must provide input.${NC}\n"
             elif ! [[ $serverSelection =~ $intCheck ]]; then
